version: "2"
services:
  webapp:
    container_name: webapp
    depends_on:
      - db
    image: app-gsa-spring:latest
    links:
      - db
    restart: always
    build: .
    ports:
    - "8080:8080"
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gaudi
      MYSQL_DATABASE: gaudi
      MYSQL_USER: gaudi
      MYSQL_PASSWORD: gaudi
    ports:
    - "3306:3306"