spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: dialects.MySQL5MyISAMDialect
  datasource:
    url: jdbc:mysql://localhost:3306/hello-gsa
    username: gaudi
    password: gaudi

server.port: 8081

allowed-origins: http://localhost:5000