spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/gaudi
    username: gaudi
    password: gaudi

server.port: 8081

allowed-origins: http://localhost:5000